// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBPPsyIvx5E2kSHyTdmUQh2wkJGaI5jXQk',
    appId: '1:338520166377:web:6dff6d55a885c2851b4578',
    messagingSenderId: '338520166377',
    projectId: 'ecommerce-2b053',
    authDomain: 'ecommerce-2b053.firebaseapp.com',
    storageBucket: 'ecommerce-2b053.appspot.com',
    measurementId: 'G-RMKZG3FK1J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBGPCqrUsbiUCBLxjcWMSwgzcrCvEaIuk8',
    appId: '1:338520166377:android:7f638a85be7a4a451b4578',
    messagingSenderId: '338520166377',
    projectId: 'ecommerce-2b053',
    storageBucket: 'ecommerce-2b053.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDhkiMu9iO-7h5MFzxq2TWLibf8TOEr8H4',
    appId: '1:338520166377:ios:7e9f4fb9104b07b41b4578',
    messagingSenderId: '338520166377',
    projectId: 'ecommerce-2b053',
    storageBucket: 'ecommerce-2b053.appspot.com',
    iosBundleId: 'com.example.ca202',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDhkiMu9iO-7h5MFzxq2TWLibf8TOEr8H4',
    appId: '1:338520166377:ios:24629a6c463b00a51b4578',
    messagingSenderId: '338520166377',
    projectId: 'ecommerce-2b053',
    storageBucket: 'ecommerce-2b053.appspot.com',
    iosBundleId: 'com.example.ca202.RunnerTests',
  );
}
